version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    reviewers:
      - 'stackrox/sensor-ecosystem'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
      - 'stackrox/sensor-ecosystem'
