version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 3
    reviewers:
      - "Maddosaurus"
      - "tommartensen"
    schedule:
      interval: 'weekly'
      day: 'wednesday'
  - package-ecosystem: 'gomod'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
    open-pull-requests-limit: 3
    reviewers:
      - "Maddosaurus"
